過去の日付を入れられないようにした
traPtitech/booQ pull request #433
Opened 2020-08-27 00:41 UTC by ntaso2051

Close #197

2020-08-27 00:45 UTC, ntaso2051 commented
![Screenshot from 2020-08-27 09-44-34](https://user-images.githubusercontent.com/53137182/91370676-f5a96f00-e849-11ea-9a32-bf18b4c33b36.png)
こんな感じです

2020-08-27 01:57 UTC, ryoha000 commented
いいんだけどクライアントの変更は全部書き換えちゃうから新しい方(https://github.com/traPtitech/booQ-UI)にしてほしい

2020-08-27 02:01 UTC, ryoha000 requested changes

2020-08-27 02:01 UTC, ryoha000 commented on client/src/components/shared/RentalForm.vue
> +      return today <= new Date(val)
```suggestion
      const oneDayMilSec = 1000 * 60 * 60 * 24
      return new Date() - new Date(val) < oneDayMilSec 
```
の方が読みやすそう

2021-05-14 02:33 UTC, sapphi-red commented
:pray:

2021-05-14 02:33 UTC, closed without merging