first commit
traPtitech/booQ pull request #504
Opened 2021-06-30 13:09 UTC by masa13535

service/booQへのbooQ botのコメントの投稿時、ユーザー名を表示するようにする。
実装方法：
router/comments.goのPostComments関数の中のmessageの定義にUserIDを追加する。
46行目
```
message := fmt.Sprintf("### コメントを投稿しました\n%v\n%v", itemInfo, comment.Text**, comment.UserID**)
```

2021-06-30 13:11 UTC, ryoha000 commented
`Close #{issue番号}`

2021-06-30 13:13 UTC, masa13535 commented
Close #{389}

2021-06-30 16:40 UTC, masa13535 commented
実装しました。レビューお願いします。

2021-07-01 12:54 UTC, ryoha000 requested changes

2021-07-01 12:54 UTC, ryoha000 commented on router/comments.go
> +	message := fmt.Sprintf("### @%s がコメントを投稿しました\n%s\n%s", comment.User.DisplayName, itemInfo, comment.Text)
```suggestion
	message := fmt.Sprintf("### @%s がコメントを投稿しました\n%s\n%s", comment.User.Name, itemInfo, comment.Text)
```
`User`のモデルはtraQがもとになってます
一つ目の画像がtraQのもの、二つ目の画像がbooQのものです
![image](https://user-images.githubusercontent.com/48485650/124127392-a01b9f80-dab6-11eb-8218-6557f6342e80.png)
![image](https://user-images.githubusercontent.com/48485650/124127303-87ab8500-dab6-11eb-874c-ecd8b64eb690.png)

投稿するメッセージの`@hoge`は`displayName`じゃなくて`name`じゃないといけないのでそう修正してほしいということです

booQの`User`モデルはここにあります
https://github.com/traPtitech/booQ/blob/e3073b38aa7953cc11ec579552f11e694b92dea0/model/users.go#L8~L13

2021-08-31 20:43 UTC, masa13535 commented
遅くなりましたが修正しました。

2021-09-01 12:29 UTC, ryoha000 approved these changes
LGTM

2021-09-01 12:29 UTC, merged